package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import hello.User;
import hello.UserRepository;

import java.util.Collection;
import java.util.Iterator;
import java.util.Optional;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/user") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @RequestMapping(path="/add/{name}/{email}", method = RequestMethod.POST) // Map ONLY POST Requests
    public @ResponseBody User addNewUser (@PathVariable("name") String name
            , @PathVariable("email") String email) {
        User user = new User(name, email);
        return userRepository.save(user);
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        return userRepository.findAll();
    }

    @GetMapping("{id}")
    public @ResponseBody User getUserById(@PathVariable Integer id) {
        final Optional<User> optionalUser = userRepository.findById(id);
        return optionalUser.map(user1 -> optionalUser.get()).orElse(User.NotFoundUser);
    }

    @DeleteMapping("{id}")
    public @ResponseBody String deleteUserById(@PathVariable Integer id){
        boolean exist = userRepository.existsById(id);
        if(!exist){
            return "User not found, can't delete it";
        }
        userRepository.deleteById(id);
        return "User deleted correctly";
    }
}